version: '3.8'

services:
  # API Server
  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    container_name: peer-evaluation-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${API_PORT:-3000}:3000"
    volumes:
      - ./src/api:/app
      - /app/node_modules
    networks:
      - app-network

  # Vue.js Frontend
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peer-evaluation-app
    restart: unless-stopped
    depends_on:
      - api
    env_file:
      - .env
    ports:
      - "${APP_PORT:-5173}:5173"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
